// <auto-generated />
namespace VirtoCommerce.DerivativeContractsModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DecimalToLong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DecimalToLong));
        
        string IMigrationMetadata.Id
        {
            get { return "201804101344035_DecimalToLong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
